import asyncio
from typing import Any, BinaryIO, Iterable, Optional

_Buffer = bytes | bytearray | memoryview

class Transport(asyncio.Transport):
    def write(self, data: _Buffer) -> None: ...
    def writelines(self, list_of_data: Iterable[_Buffer]) -> None: ...
    def sendto(self, data: _Buffer, addr: Any = None) -> None: ...
    def write_nocheck(self, data: _Buffer) -> None: ...
    def writelines_nocheck(self, list_of_data: Iterable[_Buffer]) -> None: ...
    def sendfile(
        self,
        file: BinaryIO,
        offset: int,
        count: Optional[int],
    ) -> Optional[asyncio.Future[None]]: ...

class Protocol(asyncio.BufferedProtocol):
    def is_buffered_protocol(self) -> bool: ...
    def get_local_write_buffer_size(self) -> int: ...
    def get_buffer(self, sizehint: int) -> Any: ...
    def buffer_updated(self, nbytes: int) -> None: ...
    def data_received(self, data: Any) -> None: ...

def aiofn_is_buffered_protocol(protocol: asyncio.BaseProtocol) -> bool: ...
